version: "3.3"

services:

    my_unsplash:
        build:
            context: ./app
            dockerfile: Dockerfile

        ports:
            - "8081:80"

        volumes:
            - ./app:/var/www/html/app
