name: remote ssh command
on: [push]

jobs:
  build:
    env:
      key1: ${{secrets.gcp.USERNAME}}
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - run: echo $key1
      if: ${{env.key1}} == 'erickferreira'
