name: remote ssh command
on: [push]
  
jobs:
  build:
    env:
      key1: ${{ secrets.USERNAME }}
      TEST_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      SECRETS: ${{ toJson(secrets) }}
      TEST: ${{ toJson(github) }} 
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - run: echo $key1
    - run: echo $TEST_GITHUB_TOKEN
    - run: echo $SECRETS
    - run: echo $TEST
      if: ${{env.key1}} == 'erickferreira'
