name: remote ssh commandd
on: [push]
jobs:
  etapas:
    - shell: bash
    env:
      SUPER_SECRET: ${{ secrets.USERNAME }}
    run: |
      example-command "$SUPER_SECRET"

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.GCP }}
        script: whoami
